### ISSUE TITLE
pre-commit and cookiecutter Poetry auto-generated GHA

### ISSUE THREAD

**Issue by ygworldr** [python-jsonschema/check-jsonschema#113]
Using [Cookiecutter Poetry](https://github.com/fpgmaas/cookiecutter-poetry), I get some GHA which use an `uses: ./.github/workflows/setup-poetry-env` include. This is fine on GHA but pre-commit complains that:

```
Schema validation errors were encountered.
  .github/workflows/run-checks/action.yml::$: Additional properties are not allowed ('description', 'runs' were unexpected)
  .github/workflows/run-checks/action.yml::$: 'on' is a required property
  .github/workflows/run-checks/action.yml::$: 'jobs' is a required property
Schema validation errors were encountered.
  .github/workflows/setup-poetry-env/action.yml::$: Additional properties are not allowed ('description', 'inputs', 'runs' were unexpected)
  .github/workflows/setup-poetry-env/action.yml::$: 'on' is a required property
  .github/workflows/setup-poetry-env/action.yml::$: 'jobs' is a required property
```

Is there any way to exclude those files from pre-commit?

My pre-commit configuration is:

```
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.16.1
  hooks:
  - id: check-jsonschema
    name: "Check GitHub Workflows"
    files: ^\.github/workflows/
    types: [yaml]
    args: ["--verbose", "--schemafile", "https://json.schemastore.org/github-workflow"]
```

**Comment by mondeja** [comment]
See [`exclude`](https://pre-commit.com/#top_level-exclude)

**Comment by sirosen** [comment]
`pre-commit` excludes would definitely work. Strong 👍 to that for an immediate solution.

I would recommend trying a slightly different config:
```
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.16.1
  hooks:
  - id: check-github-workflows
    args: ["--verbose"]
```

So that you use the vendored copy of the github-workflows schema. It would mean you don't get the latest schemastore schema at all times (so sometimes the vendored copy is a few commits behind schemastore), but it makes the hook behave more consistently. Changes on schemastore can't break your linting unexpectedly.

---

I'll take a look at the github workflows you're getting out of that project to see if maybe something is wrong with the hook config here, that it shouldn't be targeting those files. Or maybe there's something wrong with the upstream schema from schemastore. All of this when I get some more time to dig into this.
