### ISSUE TITLE
Validation of dates inside yaml files fails

### ISSUE THREAD

**Issue by tgillbe** [python-jsonschema/check-jsonschema#116]
Using properties with format "date-time" and "date" do not work with unquoted dates which adhere to the [tag:yaml.org,2002:timestamp format](https://yaml.org/type/timestamp.html).

Schema extract:
```json
        "offset_datetime_1": { "type": "string", "format": "date-time" },
        "offset_datetime_2": { "type": "string", "format": "date-time" },
        "offset_datetime_3": { "type": "string", "format": "date-time" },
        "offset_datetime_4": { "type": "string", "format": "date-time" },
        "offset_datetime_5": { "type": "string", "format": "date-time" },
        "offset_datetime_6": { "type": "string", "format": "date-time" },
        "local_datetime_1": { "type": "string", "format": "date-time" },
        "local_datetime_2": { "type": "string", "format": "date-time" },
        "local_datetime_3": { "type": "string", "format": "date-time" },
        "local_datetime_4": { "type": "string", "format": "date-time" },
        "local_date_1": { "type": "string", "format": "date" },
        "local_date_2": { "type": "string", "format": "date" },
        "local_time_1": { "type": "string", "format": "time" },
        "local_time_2": { "type": "string", "format": "time" },
        "local_time_3": { "type": "string", "format": "time" },
        "local_time_4": { "type": "string", "format": "time" },
```

Test file extract:
```yaml
  offset_datetime_1: 1979-05-27T07:32:00Z
  offset_datetime_2: 1979-05-27T00:32:00-07:00
  offset_datetime_3: 1979-05-27T00:32:00.999999-07:00
  offset_datetime_4: '1979-05-27T07:32:00Z'
  offset_datetime_5: '1979-05-27T00:32:00-07:00'
  offset_datetime_6: '1979-05-27T00:32:00.999999-07:00'

  naive_datetime_1: 1979-05-27T07:32:00
  local_datetime_2: 1979-05-27T00:32:00.999999

  local_date_1: 1979-05-27
  local_date_2: '1979-05-27'

  local_time_1: 07:32:00
  local_time_2: 00:32:00.999999
```

```
Schema validation errors were encountered.
  instance.yaml::$.object.offset_datetime_1: datetime.datetime(1979, 5, 27, 7, 32) is not of type 'string'
  instance.yaml::$.object.offset_datetime_2: datetime.datetime(1979, 5, 27, 7, 32) is not of type 'string'
  instance.yaml::$.object.offset_datetime_3: datetime.datetime(1979, 5, 27, 7, 32, 0, 999999) is not of type 'string'
  instance.yaml::$.object.local_datetime_2: datetime.datetime(1979, 5, 27, 0, 32, 0, 999999) is not of type 'string'
  instance.yaml::$.object.local_date_1: datetime.date(1979, 5, 27) is not of type 'string'
```
