### ISSUE TITLE
Validate usage of double quotes in expressions

### ISSUE THREAD

**Issue by awaelchli** [python-jsonschema/check-jsonschema#151]
## Motivation

We use check-jsonschema in https://github.com/Lightning-AI/lightning/ to validate all our workflow files and it works very well. We have a [GitHub action for this check here](https://github.com/Lightning-AI/utilities/blob/main/.github/workflows/check-schema.yml). 

Recently we debugged an issue in our configuration that wasn't caught by check-jsonschema. The following yaml had double quotes in the expression:

```yaml
    - name: Testing Warnings
      # the stacklevel can only be set on >=3.7
      if: ${{ (steps.skip.outputs.continue == '1') && ( matrix.python-version != "3.7" ) }}
      working-directory: tests/tests_pytorch
      # needs to run outside of `pytest`
      run: python utilities/test_warnings.py
```

which caused an error in the workflow: 

```

The workflow is not valid. .github/workflows/ci-pytorch-test-full.yml (Line: 167, Col: 11): Unexpected symbol: '"3'. Located at position 68 within expression: (steps.skip.outputs.continue == '1') && ( matrix.python-version != "3.7" )

```

And it should have used single quotes like this:

```
matrix.python-version != '3.7'
```

check-jsonschema is useful for us because we can raise these warnings directly to the author in the PR. 

## Pitch

Would it be possible to have check-jsonschema validate against correct usage of single quotes vs. double quotes? I am not familiar with how check-jsonschema works, whether this is technically possible, or whether this is in the scope of this tool at all.
