### ISSUE TITLE
Obscure schema validation error in case of missing required properties

### ISSUE THREAD

**Issue by kshpytsya** [python-jsonschema/check-jsonschema#242]
Consider the following `azure-pipelines.yml` file which passes validation:

```yaml
stages:
- stage: build

  jobs:
  - job: build

    steps:

    - task: HelmDeploy@0
      inputs:
        azureSubscriptionForACR: ''
        azureResourceGroupForACR: ''
        azureContainerRegistry: ''
```

Now, remove one of those inputs, e.g. `azureContainerRegistry`. Instead of a error hinting that a required property is missing the following completely arcane error which includes entire input yaml formatted as json is reported:

```text
Schema validation errors were encountered.
  azure-pipelines.yml::$: {'stages': [{'stage': 'build', 'jobs': [{'job': 'build', 'steps': [{'task': 'HelmDeploy@0', 'inputs': {'azureSubscriptionForACR': '', 'azureResourceGroupForACR': ''}}]}]}]} is not valid under any of the given schemas
  Underlying errors caused this.
  Best Match:
    $: {'stages': [{'stage': 'build', 'jobs': [{'job': 'build', 'steps': [{'task': 'HelmDeploy@0', 'inputs': {'azureSubscriptionForACR': '', 'azureResourceGroupForACR': ''}}]}]}]} is not of type 'string'
```

As a developer I do understand that this may be what the underlying schema validation library reports but it can hardly be called user friendly. I believe either some workaround in this tool or, better yet, an issue opened against validation library is due.
