### ISSUE TITLE
Tuple validation does not work?

### ISSUE THREAD

**Issue by mishbahr** [python-jsonschema/check-jsonschema#247]
Given this simple schema:

```json
{
  "$id":"...",
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "title":"...",
  "description":"...",
  "type":"object",
  "properties":{
    "table":{
      "type":"string"
    },
    "columns":{
      "type":"array",
      "items":{
        "type":"string"
      }
    },
    "filters":{
      "type":"array",
      "prefixItems":[
        {
          "type":"string"
        },
        {
          "type":"string"
        },
        {
          "anyOf":[
            {
              "type":"string"
            },
            {
              "type":"array",
              "items":{
                "type":"string"
              }
            }
          ]
        }
      ],
      "items":false
    }
  },
  "additionalProperties":false
}
```
And YAML file to validate:

```yaml
table: table1
columns:
  - col1
  - col2
filters:
  - ["col1", "==", "foo"]
  - ["col2", "in", ["bar", "qux"]]
```

And with this "pre-commit" config:

```yaml
  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: validate task/spec.yml
        args:
          - '--schemafile'
          - schema.json
        files: ^task/spec.yml$
```

I get a schema validation error:

```bash
$ pre-commit run check-jsonschema --file task/spec.yml
validate task/spec.yml...................................................Failed
- hook id: check-jsonschema
- exit code: 1

Schema validation errors were encountered.
  task/spec.yml::$.filters[0]: ['col1', '==', 'foo'] is not of type 'string'
  task/spec.yml::$.filters[1]: ['col2', 'in', ['bar', 'qux']] is not of type 'string'
```

I am following specs here https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

Thanks in advance.
