### ISSUE TITLE
Validation fails when expression is used in `matrix.include`

### ISSUE THREAD

**Issue by erdemedeiros** [python-jsonschema/check-jsonschema#272]
The rule `check-github-workflows` fails to validate a valid workflow when an expression is used to define the content of the attribute `matrix.include`. Example: 
```yaml
    strategy:
      matrix:
        include: ${{ fromJSON(needs.step-producing-json-without-include.outputs.result) }}
```

**Workaround:**

Move the attribute `include` as part of the generated json and and use the expression to define the content of the root `matrix`:
```yaml
    strategy:
      matrix: ${{ fromJSON(needs.step-producing-json-with-include.outputs.result) }}
```
