### ISSUE TITLE
FailedDownloadError

### ISSUE THREAD

**Issue by kaihendry** [python-jsonschema/check-jsonschema#294]
In order to check files in config/*.yaml I am using:

```
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.23.3
      hooks:
        - id: check-github-workflows
        - id: check-jsonschema
          name: Check test configs
          files: ^config/[^/]+$
          types: [yaml]
          args: ["--schemafile", "https://raw.githubusercontent.com/EVerest/everest-framework/main/schemas/config.yaml"]
```

But it fails with:

```
Check test configs.......................................................Failed
- hook id: check-jsonschema
- duration: 0.56s
- exit code: 1

Error: Unexpected Error building schema validator
FailedDownloadError: got responses with status=200, retries exhausted
  in "/Users/hendry/.cache/pre-commit/repoircq8841/py_env-python3.10/lib/python3.10/site-packages/check_jsonschema/checker.py", line 52
  >>> return self._schema_loader.get_validator(

make: *** [run] Error 1
```

I don't understand why it fails with status 200 success?
