### ISSUE TITLE
GitLab CI yaml vaiarbles failing

### ISSUE THREAD

**Issue by KindDragon** [python-jsonschema/check-jsonschema#304]
My .gitlab-ci.yml start failing after I add variables to my job:
```
 variables:
  GLOBAL_VAR: "A global variable"

job1:
  variables:
    JOB_VAR: "A job variable"
    JOB_VAR2: "A job variable"
  script:
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"

job2:
  script:
    - echo "Variables are '$GLOBAL_VAR' and '$JOB_VAR'"
```
https://docs.gitlab.com/ee/ci/variables/

**Comment by sirosen** [comment]
What error are you receiving? Your file, as pasted here, isn't valid YAML, so it fails to parse (leading space on the first line).
When I fix that and run with the gitlab CI schema, the file passes.

**Comment by sirosen** [comment]
Absent any further information, I'm closing this as user-error. I don't think there's a bug here -- at least, there isn't one that I'm able to detect.
If there's more info that clarifies that this is a problem with `check-jsonschema` or the bundled schema, please feel free to reopen!

**Comment by KindDragon** [comment]
Sorry, misdiagnosed it. Two variables blocks cause it, but this works in gitlab ci.
```
unit-test-job:   # This job runs in the test stage.
  variables:
    GIT_SUBMODULE_STRATEGY: none

  stage: test    # It only starts when the job in the build stage completes successfully.

  variables:
    JOB_VAR2: "A job variable"
```
