### ISSUE TITLE
Support verbose output in pre-commit hook

### ISSUE THREAD

**Issue by rpdelaney** [python-jsonschema/check-jsonschema#322]
In pre-commit I got an error followed by this:
```
  1 other errors were produced. Use '--verbose' to see all errors.
```
I'd like to have an option to print all the errors immediately so I can get started on fixing them without having to enter more commands.

**Comment by sirosen** [comment]
You can update your `.pre-commit-config.yaml` to have
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.26.3
  hooks:
    - id: whatever-hook-you-are-using-here-this-is-just-a-made-up-string
      args: ["--verbose"]  # or "-v" if you want it to be shorter
```

Does that not address your needs?
