### ISSUE TITLE
Support for `default.json` for `renovate`

### ISSUE THREAD

**Issue by paddyroddy** [python-jsonschema/check-jsonschema#337]
If you have a [shareable preset](https://docs.renovatebot.com/config-presets/#github-hosted-presets) then `renovate` recommends having it in a repo called `renovate-config` and have the file in there called `default.json`, i.e. https://github.com/paddyroddy/renovate-config/blob/main/default.json. I would like to validate that this `default.json` is valid, but currently it would be skipped.

**Comment by sirosen** [comment]
I believe that this is supported today by taking the renovate schema and running it explicitly against the file.

e.g. In `pre-commit` config:
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.0
  hooks:
  - id: check-renovate-default
    name: Validate default.json Renovate Config
    description: 'Validate Renovate config in default.json'
    entry: check-jsonschema --builtin-schema vendor.renovate
    files: ^default\.json$
```

You can also run it manually with
```shell
check-jsonschema --builtin-schema vendor.renovate default.json
```
(The pre-commit config I showed is just the config for running this exact command with some nice description.)

I don't see any clear way to support the `default.json` name out of the box -- it's not a renovate-specific filename outside of the broader context that _if_ you already know that it's a renovate config, it's the recommended name.

---

Does that satisfy your needs? If not, I'll need more info about the context to understand.

**Comment by paddyroddy** [comment]
Yes, that would work nicely!

**Comment by paddyroddy** [comment]
Just to check (might have missed something obvious), I can see how that can go into `.pre-commit-hooks.yaml`, is there a way I can - as a user - use that in my `.pre-commit-config.yaml`?

**Comment by sirosen** [comment]
That config should be valid for pre-commit-config.

The hooks config looks very similar, so I can understand the confusion. If I've made a mistake such that it's not valid for the user config file, let me know and we can fix it, but it looks right to me (from a mobile device, so I can't test it at the moment).

**Comment by paddyroddy** [comment]
Think it was just a case of changing the `id` to match the existing one
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.0
  hooks:
  - id: check-renovate
    name: Validate default.json Renovate Config
    description: 'Validate Renovate config in default.json'
    entry: check-jsonschema --builtin-schema vendor.renovate
    files: ^default\.json$
```
