### ISSUE TITLE
AttributeError not parsing schema correctly.

### ISSUE THREAD

**Issue by blade2005** [python-jsonschema/check-jsonschema#376]
I use Taskfile a lot and want to make sure my yaml files are correct.

Fortunately there's this project and [Taskfile](https://taskfile.dev/) publishes their [schema](https://taskfile.dev/schema.json)

Save the below as `poc.Taskfile.yaml`
```yaml
version: 3
tasks:
  default:
    cmds:
      - echo hi
      - defer: echo bye
      - echo hi again
```

Run the following
```shell
pipx run check-jsonschema --verbose --schemafile https://taskfile.dev/schema.json poc.Taskfile.yaml
```

[output](https://gist.github.com/blade2005/cc30bf9319c672234b8b93fd02b3e5e2)

Running the task works fine indicating the application sees it as a valid file

```
$ task -t poc.Taskfile.yaml
task: [default] echo hi
hi
task: [default] echo hi again
hi again
task: [default] echo bye
bye
```

The error seems to be focused around the `defer` line. If I comment out the line with the defer jsonschema says it's valid.
