### ISSUE TITLE
Validation passes for misspelled optional child properties in Google Cloud Build schema

### ISSUE THREAD

**Issue by jrdnbradford** [python-jsonschema/check-jsonschema#385]
I am utilizing `0.27.3` with `pre-commit` to run the `check-cloudbuild` hook:
```yaml
repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3 
  hooks:
    - id: check-cloudbuild
      files: ^cloudbuild/.*\.yaml$
      args: ["--verbose", "--traceback-mode", "full"]
```

Validation doesn't appear to occur for child property names. For instance, it rightfully catches 2 errors in the following `yaml`:

```yaml
timeout: 30

steps:
- id: 'terraform-init-base'
  name: hashicorp/terraform:${_TF_TAG}
  dir: 'modules/base'
  waitFor: ['-']
  args: 'init'
```

```bash
Schema validation errors were encountered.
  cloudbuild/terraform-base-plan.yaml::$.steps[0].args: 'init' is not of type 'array'
  cloudbuild/terraform-base-plan.yaml::$.timeout: 30 is not of type 'string'
```

It will even catch if the required  `steps` is misspelled:
```yaml

stps: # Misspelled
- id: 'terraform-init-base'
  name: hashicorp/terraform:${_TF_TAG}
  dir: 'modules/base'
  waitFor: ['-']
  args: [ 'init']
```
```bash
Schema validation errors were encountered.
  cloudbuild/terraform-base-plan.yaml::$: 'steps' is a required property
```

But it does not catch misspelling of optional child properties under `steps`:
```yaml
steps:
- id: 'terraform-init-base'
  nam: hashicorp/terraform:${_TF_TAG} # Misspelled
  dr: 'modules/base' # Misspelled
  watFor: ['-'] # Misspelled
  ags: ['init' ] # Misspelled
```
```bash
Validate Google Cloud Build config.......................................Passed
```

I had presumed that validation would catch `nam` (`name`), `dr` (`dir`), `watFor` (`waitFor`) and `ags` (`args`). These are listed as possible values in the [Cloud Build Schema](https://json.schemastore.org/cloudbuild.json) under `steps`. Is this expected behavior, or am I missing something?
