### ISSUE TITLE
Non-JSON files ignored despite --default-type being set

### ISSUE THREAD

**Issue by cegekaJG** [python-jsonschema/check-jsonschema#402]
I'd like to set up a pre-commit hook that validates against the `.code-workspace` file used by VS Code, but check-jsonschema always seems to ignore any files that don't end with `.json` or `.yml`.

Here's my current config:

```yml
repos:
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.28.0
      hooks:
          - id: check-jsonschema
            args:
                [
                    "--default-filetype",
                    "json",
                    "--schemafile",
                    ".schemas/workspace.schema.json",
                ]
```

And here's my terminal, trying to validate the file:

``` shell
PS C:\Users\cegekaJG\Documents\base> git --version
git version 2.39.0.windows.1
PS C:\Users\cegekaJG\Documents\clients\base> git diff --name-only --staged
Base.code-workspace
PS C:\Users\cegekaJG\Documents\clients\base> pre-commit run check-jsonschema -v
Validate files with jsonschema.......................(no files to check)Skipped
- hook id: check-jsonschema
```

From what I understand, the flag `--default-filetype` should make it so any file that doesn't end with `.json` or `.yml` will be interpreted as a JSON file, but that doesn't seem to be happening.

**Comment by sirosen** [comment]
What's probably happening is that `pre-commit` is not even passing the files to `check-jsonschema`.

In the context of `pre-commit`, hooks are only run on files of the matching types. `check-jsonschema` and `pre-commit` each have their own logic and options for controlling how files are handled, so the options are sometimes a little confusing (of necessity, sadly).

What you'll probably want is to not bother with `--default-filetype` (it defaults to JSON) and instead adjust the `types` and `types_or` fields in pre-commit. The repo-provided hook is defined with
```yaml
types_or: [json,yaml]
```
meaning it will run on any file which `pre-commit` identifies as JSON or YAML.

For example, here's a config which runs `check-jsonschema` on every file in a directory named `json-data/`, regardless of type:
```yaml
repos:
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.28.0
      hooks:
          - id: check-jsonschema
            args: ["--schemafile", "schema.json"]
            types_or: []  # explicitly disable types_or matching
            files: "^json-data/.*"
```

(NB: I haven't tested this out. It should work though.)

According to [pre-commit's documentation on hooks](https://pre-commit.com/#creating-new-hooks), `types_or` defaults to `[]`, so this is just resetting it to the default empty-list value.
So we can turn off type-based matching and enable explicit filename-based matching.

You'll need to decide how you want to discover and pass files to `check-jsonschema` if you're using it in this way.
You could also do things like
```
types_or: [json,yaml,toml]
```
to configure a specific set of (`pre-commit`-supported) filetypes.
