### ISSUE TITLE
check-azure-pipelines: doesn't handle default value for boolean parameter properly

### ISSUE THREAD

**Issue by karunpoudel-chr** [python-jsonschema/check-jsonschema#403]
Following `azure-pipelines.yml` although valid gives pre-commit error:

```yaml
parameters:
  - name: myBoolean
    displayName: myboolean
    type: boolean
    default: true

steps:
  - bash: echo "{{ parameters.myBoolean}}"
```
gives error:
`$.parameters[0].default: True is not of type 'string'`

Following works (in both pre-commit and azure pipeline) but doesn't look correct to have `'true'` for boolean

```yaml
parameters:
  - name: myBoolean
    displayName: myboolean
    type: boolean
    default: 'true'

steps:
  - bash: echo "{{ parameters.myBoolean}}"
```

Setup:
```yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-azure-pipelines
```
