### ISSUE TITLE
[BUG] RegEx not recognised

### ISSUE THREAD

**Issue by patvdleer** [python-jsonschema/check-jsonschema#436]
Using the `gitlab-ci` validation my RegEx on coverage isn't recognised as such while it does work.

```
Schema validation errors were encountered.
  .gitlab-ci.yml::$.unittests:python-3.12.coverage: '/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/' is not a 'regex'
```

```yaml
unittests:python-3.12:
  <<: *unittests
  image: python:3.12
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
```
