### ISSUE TITLE
Vendor mergify schema

### ISSUE THREAD

**Issue by hofbi** [python-jsonschema/check-jsonschema#487]
It would be cool that also have mergify available as built in schema and pre defined hook. They provide a [their schema](https://docs.mergify.com/mergify-configuration-schema.json) in their [docs](https://docs.mergify.com/configuration/file-format/#configuration-file-name).

This is the config I have for now to make this available without vendoring:

```yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-jsonschema
        alias: check-mergify
        args: ["--schemafile", "https://docs.mergify.com/mergify-configuration-schema.json"]
        files:
          (?x)^(
            .github/mergify.yml|
            .mergify.yml|
            .mergify/config.yml
          )
        types: [yaml]
```
