### ISSUE TITLE
Gitlab ci `!reference` in cache is not validating correctly anymore

### ISSUE THREAD

**Issue by balihb** [python-jsonschema/check-jsonschema#498]
Since the new update , for this code:

```yaml
  cache:
    - paths:
        - ${PIP_CACHE_DIR}
      key:
        prefix: "pip-${PYTHON_VERSION}-${CI_JOB_NAME}-${TOX_VERSION}"
        files:
          - requirements.txt
    - !reference [ .apt:cache, cache ]
```

I'm getting this error:

```text
  .gitlab-ci.yml::$.test.cache: [{'paths': ['${PIP_CACHE_DIR}'], 'key': {'prefix': 'pip-${PYTHON_VERSION}-${CI_JOB_NAME}-${TOX_VERSION}', 'files': ['requirements.txt']}}, ['.apt:cache', 'cache']] is not valid under any of the given schemas
  Underlying errors caused this.

  Best Match:
    $.test.cache: [{'paths': ['${PIP_CACHE_DIR}'], 'key': {'prefix': 'pip-${PYTHON_VERSION}-${CI_JOB_NAME}-${TOX_VERSION}', 'files': ['requirements.txt']}}, ['.apt:cache', 'cache']] is not of type 'object'
  Best Deep Match:
    $.test.cache[1]: ['.apt:cache', 'cache'] is not of type 'object'
```

**Comment by sirosen** [comment]
The underlying issue here is almost certainly that `!reference` is not supported by `check-jsonschema`.
So the sample you gave is treated exactly the same as
```yaml
  cache:
    - paths:
        - ${PIP_CACHE_DIR}
      key:
        prefix: "pip-${PYTHON_VERSION}-${CI_JOB_NAME}-${TOX_VERSION}"
        files:
          - requirements.txt
    - [ .apt:cache, cache ]
```

In the general case, I don't think `!reference` can be supported. In the narrow case of loading from a local path, we can add support, so I'm currently thinking of this as a feature request to that effect. See also #274

If you agree that this is the issue, I'd like to close as a duplicate of #274. If you _don't_ agree, I think I'll need more information.
