### ISSUE TITLE
New builtin schema type: CITATION.cff?

### ISSUE THREAD

**Issue by henryiii** [python-jsonschema/check-jsonschema#502]
Would it make sense to add CITATION.cff to the built-in schemas? It would be nice to have a flag and a pre-commit check for it, currently it requires:

```bash
uvx check-jsonschema --schemafile https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json --no-cache --default-filetype yaml CITATION.cff
```

and

```yaml
      - id: check-jsonschema
        name: Validate CITATION.cff
        files: ^CITATION.cff$
        types_or: [file]
        args:
          - --schemafile=https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json
          - --default-filetype=yaml
          - --no-cache
```

Ref for CITATION.cff: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files and links from there.

PS: I'm not sure why `--no-cache` is required, it gets a completely incorrect file if not passed. Maybe it's caching on the name `schema.json`?
